import { createSwaggerSpec } from "next-swagger-doc";

export const getApiDocs = () => {
  return createSwaggerSpec({
    apiFolder: "src/app/api",
    definition: {
      openapi: "3.0.0",
      info: {
        title: "Life Note API",
        version: "1.0.0",
        description: "API documentation for the Life Note backend.",
      },
      servers: [{ url: "/api" }],
      tags: [
        { name: "Auth", description: "Authentication and account management" },
        { name: "Notes", description: "Create, organize, and search nested notes" },
        { name: "SOPs", description: "Create and manage Standard Operating Procedures" },
        { name: "Tasks", description: "Create and manage personal tasks" },
        { name: "Workspaces", description: "Shared workspaces, members and roles" },
        { name: "Projects", description: "Projects (issue key prefixes) and their components" },
        { name: "Planning", description: "Sprints, epics and releases (fix versions)" },
        { name: "Issues", description: "Issues: board/list queries, detail, updates, search" },
        {
          name: "Issue details",
          description:
            "Acceptance criteria, relations, comments, work logs, attachments, watchers, dev links and activity",
        },
        { name: "Runbooks", description: "SOP executions: SOPs running against issues/tasks/notes, step actions, approvals, GitHub" },
        { name: "Notifications", description: "In-app notifications for @mentions and assignments" },
      ],
      components: {
        securitySchemes: {
          // NextAuth (Auth.js) v5 with the JWT session strategy authenticates via an
          // httpOnly session cookie, not an Authorization header — sign in through
          // POST /api/auth/callback/credentials (or the /login page) to obtain it.
          CookieAuth: {
            type: "apiKey",
            in: "cookie",
            name: "authjs.session-token",
            description:
              "Session cookie set by NextAuth after signing in via POST /api/auth/callback/credentials or the /login page. In production this is __Secure-authjs.session-token.",
          },
        },
        parameters: {
          WorkspaceId: { in: "path", name: "workspaceId", required: true, schema: { type: "string" } },
          ProjectId: { in: "path", name: "projectId", required: true, schema: { type: "string" } },
          IssueId: { in: "path", name: "issueId", required: true, schema: { type: "string" } },
          Limit: { in: "query", name: "limit", schema: { type: "integer", minimum: 1, maximum: 100, default: 50 } },
          Offset: { in: "query", name: "offset", schema: { type: "integer", minimum: 0, default: 0 } },
        },
        responses: {
          BadRequest: {
            description: "Invalid input.",
            content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } },
          },
          Unauthorized: {
            description: "Not authenticated.",
            content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } },
          },
          Forbidden: {
            description: "Your role doesn't allow this action.",
            content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } },
          },
          NotFound: {
            description: "Not found, or not in one of your workspaces.",
            content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } },
          },
          Conflict: {
            description: "Conflicts with existing data.",
            content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } },
          },
          Deleted: {
            description: "Deleted.",
            content: { "application/json": { schema: { $ref: "#/components/schemas/Message" } } },
          },
        },
        schemas: {
          Error: {
            type: "object",
            properties: {
              error: {
                type: "object",
                required: ["code", "message"],
                properties: {
                  code: {
                    type: "string",
                    description:
                      "Stable machine-readable code, e.g. VALIDATION_ERROR, UNAUTHORIZED, FORBIDDEN, NOT_FOUND, CONFLICT, RATE_LIMITED, INVALID_CREDENTIALS, EMAIL_NOT_VERIFIED, INVALID_OTP, OTP_COOLDOWN, INTERNAL_ERROR.",
                  },
                  message: { type: "string", description: "Human-readable message." },
                  details: {
                    type: "array",
                    description: "Per-field issues (VALIDATION_ERROR only).",
                    items: {
                      type: "object",
                      properties: { path: { type: "string" }, message: { type: "string" } },
                    },
                  },
                },
              },
            },
          },
          Message: {
            type: "object",
            properties: {
              message: { type: "string" },
            },
          },
          Note: {
            type: "object",
            properties: {
              id: { type: "string" },
              userId: { type: "string" },
              parentId: { type: "string", nullable: true },
              title: { type: "string" },
              content: { type: "string" },
              createdAt: { type: "string", format: "date-time" },
              updatedAt: { type: "string", format: "date-time" },
            },
          },
          NoteSummary: {
            type: "object",
            properties: {
              id: { type: "string" },
              title: { type: "string" },
              parentId: { type: "string", nullable: true },
              createdAt: { type: "string", format: "date-time" },
              updatedAt: { type: "string", format: "date-time" },
              childCount: {
                type: "integer",
                description: "Only present when listing via GET /notes.",
              },
            },
          },
          Sop: {
            type: "object",
            properties: {
              id: { type: "string" },
              userId: { type: "string", description: "The author." },
              workspaceId: {
                type: "string",
                nullable: true,
                description: "Workspace the SOP is shared with; null = private to the author.",
              },
              title: { type: "string" },
              content: { type: "string" },
              user: {
                allOf: [{ $ref: "#/components/schemas/User" }],
                description: "The author. Present on list and get.",
              },
              version: {
                type: "integer",
                description: "Increments by 1 every time title, content or steps change.",
              },
              steps: {
                type: "array",
                description: "Only present on GET /sops/{id}.",
                items: { $ref: "#/components/schemas/SopStep" },
              },
              createdAt: { type: "string", format: "date-time" },
              updatedAt: { type: "string", format: "date-time" },
            },
          },
          Task: {
            type: "object",
            properties: {
              id: { type: "string" },
              userId: { type: "string" },
              title: { type: "string" },
              content: { type: "string" },
              status: { type: "string", enum: ["TODO", "IN_PROGRESS", "DONE"] },
              dueDate: { type: "string", format: "date-time", nullable: true },
              createdAt: { type: "string", format: "date-time" },
              updatedAt: { type: "string", format: "date-time" },
            },
          },
          User: {
            type: "object",
            properties: {
              id: { type: "string" },
              name: { type: "string", nullable: true },
              email: { type: "string" },
              image: { type: "string", nullable: true },
            },
          },
          SopStepType: {
            type: "string",
            enum: ["INSTRUCTION", "CHECKLIST", "USER_ACTION", "APPROVAL", "TESTING", "GITHUB_ACTION", "CONDITION", "CONFIRMATION", "AUTOMATED_ACTION"],
          },
          SopCondition: {
            type: "object",
            description:
              "JSON condition tree. Leaf: { field, operator, value }, where field is a dotted path into the context — " +
              "issue.{type,status,priority,labels,storyPoints,componentId,component.name,project.key,fields.<custom>,...}, " +
              "task.{title,status}, note.{title,depth,path,module.title}, steps.<stepKey>.{status,result,attempt,approvals,rejections}, event.{type,step.key,step.result}, " +
              "execution.{status,assignmentType}. Combine with { all: [...] } (AND), { any: [...] } (OR), { not: {...} }. " +
              "Operators: EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS, IN, NOT_IN, GREATER_THAN, GREATER_THAN_OR_EQUAL, " +
              "LESS_THAN, LESS_THAN_OR_EQUAL, STARTS_WITH, ENDS_WITH, EXISTS, NOT_EXISTS.",
            example: {
              all: [
                { field: "issue.type", operator: "EQUALS", value: "BUG" },
                { field: "issue.fields.riskLevel", operator: "IN", value: ["HIGH", "CRITICAL"] },
              ],
            },
          },
          SopAction: {
            type: "object",
            required: ["type"],
            description:
              "One action from the registry: SET_ISSUE_STATUS {status}, SET_TASK_STATUS {status}, SET_RUNBOOK_STATUS {status: FAILED|BLOCKED|SKIPPED}, " +
              "GO_TO_STEP {stepKey}, SKIP_STEP {stepKey}, REQUIRE_APPROVALS {stepKey, count}, SET_STEP_CONFIG {stepKey, config}, " +
              "ADD_LABEL {label}, REMOVE_LABEL {label}, ASSIGN_ISSUE {userId|null}, SET_ISSUE_FIELD {field, value}.",
            properties: { type: { type: "string" } },
            example: { type: "REQUIRE_APPROVALS", stepKey: "tech-lead-approval", count: 2 },
          },
          SopRuleInput: {
            type: "object",
            properties: {
              name: { type: "string" },
              trigger: {
                type: "string",
                enum: ["EXECUTION_STARTED", "EXECUTION_COMPLETED", "STEP_STARTED", "STEP_COMPLETED", "STEP_FAILED", "STEP_BLOCKED", "STEP_SKIPPED", "ISSUE_UPDATED", "ISSUE_STATUS_CHANGED", "TASK_UPDATED", "NOTE_UPDATED"],
              },
              condition: { $ref: "#/components/schemas/SopCondition" },
              actions: { type: "array", items: { $ref: "#/components/schemas/SopAction" } },
              enabled: { type: "boolean", default: true },
            },
          },
          SopRule: {
            allOf: [
              { $ref: "#/components/schemas/SopRuleInput" },
              {
                type: "object",
                properties: {
                  id: { type: "string" },
                  sopId: { type: "string" },
                  createdAt: { type: "string", format: "date-time" },
                  updatedAt: { type: "string", format: "date-time" },
                },
              },
            ],
          },
          SopStep: {
            type: "object",
            properties: {
              id: { type: "string" },
              sopId: { type: "string" },
              key: { type: "string", description: "Stable handle for conditions/rules, unique in the SOP.", example: "qa-testing" },
              position: { type: "integer" },
              title: { type: "string" },
              description: { type: "string" },
              command: { type: "string", nullable: true },
              requiresSignoff: { type: "boolean" },
              type: { $ref: "#/components/schemas/SopStepType" },
              config: {
                type: "object",
                description:
                  "By type — CHECKLIST: { items: [{ id, label, required }] }; APPROVAL: { requiredApprovals, approvers?: { userIds, roles, projectLead } }; " +
                  "GITHUB_ACTION: { event: PR_OPENED|PR_MERGED|CHECKS_PASSED, baseBranch?, allowManualCompletion? }; " +
                  "CONDITION: { condition, onTrue?, onFalse? } with { then: CONTINUE|FAIL|BLOCK|GO_TO_STEP, stepKey? }; " +
                  "AUTOMATED_ACTION: { actions: SopAction[] }. Any manual type: { allowedUserIds?, allowedRoles? }.",
              },
              condition: {
                allOf: [{ $ref: "#/components/schemas/SopCondition" }],
                nullable: true,
                description: "When set, the step only runs if this holds when it's reached; otherwise it's SKIPPED.",
              },
              createdAt: { type: "string", format: "date-time" },
              updatedAt: { type: "string", format: "date-time" },
            },
          },
          Workspace: {
            type: "object",
            properties: {
              id: { type: "string" },
              name: { type: "string" },
              role: { type: "string", enum: ["OWNER", "ADMIN", "MEMBER"], description: "The caller's role in this workspace." },
              createdAt: { type: "string", format: "date-time" },
              updatedAt: { type: "string", format: "date-time" },
            },
          },
          WorkspaceMember: {
            type: "object",
            properties: {
              userId: { type: "string" },
              role: { type: "string", enum: ["OWNER", "ADMIN", "MEMBER"] },
              createdAt: { type: "string", format: "date-time" },
              user: { $ref: "#/components/schemas/User" },
            },
          },
          Project: {
            type: "object",
            properties: {
              id: { type: "string" },
              workspaceId: { type: "string" },
              key: { type: "string", example: "AUTH" },
              name: { type: "string" },
              description: { type: "string" },
              color: { type: "string", nullable: true },
              leadId: { type: "string", nullable: true },
              issueCounter: { type: "integer" },
              createdAt: { type: "string", format: "date-time" },
              updatedAt: { type: "string", format: "date-time" },
            },
          },
          Component: {
            type: "object",
            properties: {
              id: { type: "string" },
              projectId: { type: "string" },
              name: { type: "string" },
              description: { type: "string" },
              createdAt: { type: "string", format: "date-time" },
              updatedAt: { type: "string", format: "date-time" },
            },
          },
          Sprint: {
            type: "object",
            properties: {
              id: { type: "string" },
              workspaceId: { type: "string" },
              name: { type: "string" },
              goal: { type: "string" },
              status: { type: "string", enum: ["PLANNED", "ACTIVE", "COMPLETED"] },
              startDate: { type: "string", format: "date-time", nullable: true },
              endDate: { type: "string", format: "date-time", nullable: true },
              createdAt: { type: "string", format: "date-time" },
              updatedAt: { type: "string", format: "date-time" },
            },
          },
          Epic: {
            type: "object",
            properties: {
              id: { type: "string" },
              workspaceId: { type: "string" },
              name: { type: "string" },
              description: { type: "string" },
              color: { type: "string", nullable: true },
              status: { type: "string", enum: ["OPEN", "IN_PROGRESS", "DONE"] },
              startDate: { type: "string", format: "date-time", nullable: true },
              targetDate: { type: "string", format: "date-time", nullable: true },
              createdAt: { type: "string", format: "date-time" },
              updatedAt: { type: "string", format: "date-time" },
            },
          },
          Release: {
            type: "object",
            properties: {
              id: { type: "string" },
              workspaceId: { type: "string" },
              name: { type: "string" },
              description: { type: "string" },
              status: { type: "string", enum: ["UNRELEASED", "RELEASED", "ARCHIVED"] },
              releaseDate: { type: "string", format: "date-time", nullable: true },
              createdAt: { type: "string", format: "date-time" },
              updatedAt: { type: "string", format: "date-time" },
            },
          },
          PlanningStats: {
            type: "object",
            properties: {
              byStatus: {
                type: "object",
                additionalProperties: { type: "integer" },
                example: { TODO: 3, IN_PROGRESS: 2, DONE: 5 },
              },
              total: { type: "integer" },
              done: { type: "integer" },
              percent: { type: "integer" },
              points: { type: "integer", description: "Sum of story points." },
              donePoints: { type: "integer" },
            },
          },
          IssueRef: {
            type: "object",
            properties: {
              id: { type: "string" },
              key: { type: "string", example: "AUTH-104" },
              title: { type: "string" },
              status: { type: "string", enum: ["BACKLOG", "TODO", "IN_PROGRESS", "IN_REVIEW", "DONE", "CANCELLED"] },
              type: { type: "string", enum: ["STORY", "TASK", "BUG", "SECURITY", "SPIKE"] },
              priority: { type: "string", enum: ["URGENT", "HIGH", "MEDIUM", "LOW", "NONE"] },
            },
          },
          Issue: {
            type: "object",
            properties: {
              id: { type: "string" },
              workspaceId: { type: "string" },
              projectId: { type: "string" },
              number: { type: "integer" },
              key: { type: "string", example: "AUTH-104" },
              type: { type: "string", enum: ["STORY", "TASK", "BUG", "SECURITY", "SPIKE"] },
              title: { type: "string" },
              description: { type: "string", description: "Markdown." },
              status: { type: "string", enum: ["BACKLOG", "TODO", "IN_PROGRESS", "IN_REVIEW", "DONE", "CANCELLED"] },
              priority: { type: "string", enum: ["URGENT", "HIGH", "MEDIUM", "LOW", "NONE"] },
              storyPoints: { type: "integer", nullable: true },
              labels: { type: "array", items: { type: "string" } },
              position: { type: "number", description: "Sort order within a board column." },
              estimateMinutes: { type: "integer", nullable: true },
              dueDate: { type: "string", format: "date-time", nullable: true },
              slaDueAt: { type: "string", format: "date-time", nullable: true },
              resolvedAt: { type: "string", format: "date-time", nullable: true, description: "Set when status becomes DONE." },
              assigneeId: { type: "string", nullable: true },
              reporterId: { type: "string" },
              parentId: { type: "string", nullable: true },
              componentId: { type: "string", nullable: true },
              epicId: { type: "string", nullable: true },
              sprintId: { type: "string", nullable: true },
              releaseId: { type: "string", nullable: true },
              createdAt: { type: "string", format: "date-time" },
              updatedAt: { type: "string", format: "date-time" },
            },
          },
          IssueListItem: {
            type: "object",
            properties: {
              id: { type: "string" },
              workspaceId: { type: "string" },
              projectId: { type: "string" },
              number: { type: "integer" },
              key: { type: "string", example: "AUTH-104" },
              type: { type: "string", enum: ["STORY", "TASK", "BUG", "SECURITY", "SPIKE"] },
              title: { type: "string" },
              description: { type: "string", description: "Markdown." },
              status: { type: "string", enum: ["BACKLOG", "TODO", "IN_PROGRESS", "IN_REVIEW", "DONE", "CANCELLED"] },
              priority: { type: "string", enum: ["URGENT", "HIGH", "MEDIUM", "LOW", "NONE"] },
              storyPoints: { type: "integer", nullable: true },
              labels: { type: "array", items: { type: "string" } },
              position: { type: "number", description: "Sort order within a board column." },
              estimateMinutes: { type: "integer", nullable: true },
              dueDate: { type: "string", format: "date-time", nullable: true },
              slaDueAt: { type: "string", format: "date-time", nullable: true },
              resolvedAt: { type: "string", format: "date-time", nullable: true, description: "Set when status becomes DONE." },
              assigneeId: { type: "string", nullable: true },
              reporterId: { type: "string" },
              parentId: { type: "string", nullable: true },
              componentId: { type: "string", nullable: true },
              epicId: { type: "string", nullable: true },
              sprintId: { type: "string", nullable: true },
              releaseId: { type: "string", nullable: true },
              createdAt: { type: "string", format: "date-time" },
              updatedAt: { type: "string", format: "date-time" },
              assignee: { allOf: [{ $ref: "#/components/schemas/User" }], nullable: true },
              component: { type: "object", nullable: true, properties: { id: { type: "string" }, name: { type: "string" } } },
              epic: { type: "object", nullable: true, properties: { id: { type: "string" }, name: { type: "string" }, color: { type: "string", nullable: true } } },
              sprint: { type: "object", nullable: true, properties: { id: { type: "string" }, name: { type: "string" }, status: { type: "string" } } },
              release: { type: "object", nullable: true, properties: { id: { type: "string" }, name: { type: "string" } } },
              _count: { type: "object", properties: { subtasks: { type: "integer" }, comments: { type: "integer" }, attachments: { type: "integer" } } },
            },
          },
          IssueRelation: {
            type: "object",
            properties: {
              id: { type: "string" },
              type: { type: "string", enum: ["BLOCKS", "RELATES_TO", "DUPLICATES"] },
              direction: { type: "string", enum: ["outward", "inward"] },
              label: { type: "string", example: "is blocked by" },
              issue: { $ref: "#/components/schemas/IssueRef" },
            },
          },
          AcceptanceCriterion: {
            type: "object",
            properties: {
              id: { type: "string" },
              issueId: { type: "string" },
              text: { type: "string" },
              done: { type: "boolean" },
              position: { type: "integer" },
              createdAt: { type: "string", format: "date-time" },
              updatedAt: { type: "string", format: "date-time" },
            },
          },
          DevLink: {
            type: "object",
            properties: {
              id: { type: "string" },
              issueId: { type: "string" },
              createdById: { type: "string", nullable: true },
              type: { type: "string", enum: ["BRANCH", "PULL_REQUEST", "COMMIT", "BUILD"] },
              title: { type: "string" },
              url: { type: "string", nullable: true },
              externalId: { type: "string", nullable: true, description: "e.g. PR number, commit SHA, build id." },
              status: { type: "string", nullable: true, description: "Free text, e.g. open, merged, passing." },
              createdAt: { type: "string", format: "date-time" },
              updatedAt: { type: "string", format: "date-time" },
            },
          },
          RunbookStep: {
            type: "object",
            properties: {
              id: { type: "string" },
              runbookId: { type: "string" },
              key: { type: "string" },
              position: { type: "integer" },
              title: { type: "string" },
              description: { type: "string" },
              command: { type: "string", nullable: true },
              requiresSignoff: { type: "boolean" },
              type: { $ref: "#/components/schemas/SopStepType" },
              config: { type: "object" },
              condition: { allOf: [{ $ref: "#/components/schemas/SopCondition" }], nullable: true },
              status: {
                type: "string",
                enum: ["PENDING", "IN_PROGRESS", "VERIFIED", "FAILED", "BLOCKED", "SKIPPED"],
                description: "VERIFIED = completed.",
              },
              result: { type: "string", nullable: true, description: "PASSED/FAILED, APPROVED/REJECTED, TRUE/FALSE, ..." },
              data: { type: "object", description: "Type-specific state, e.g. CHECKLIST { checkedItems }." },
              attempt: { type: "integer", description: "Increments on each retry/rewind." },
              notes: { type: "string" },
              output: { type: "string" },
              executor: { type: "string", nullable: true, example: "automated pipeline #4418" },
              completedById: { type: "string", nullable: true },
              completedBy: { allOf: [{ $ref: "#/components/schemas/User" }], nullable: true },
              approvals: {
                type: "array",
                items: {
                  type: "object",
                  properties: {
                    id: { type: "string" },
                    userId: { type: "string" },
                    user: { $ref: "#/components/schemas/User" },
                    decision: { type: "string", enum: ["APPROVED", "REJECTED"] },
                    comment: { type: "string" },
                    attempt: { type: "integer" },
                    current: { type: "boolean", description: "Counts toward the step's current attempt." },
                    createdAt: { type: "string", format: "date-time" },
                  },
                },
              },
              startedAt: { type: "string", format: "date-time", nullable: true },
              completedAt: { type: "string", format: "date-time", nullable: true },
              createdAt: { type: "string", format: "date-time" },
              updatedAt: { type: "string", format: "date-time" },
            },
          },
          RunbookEvent: {
            type: "object",
            properties: {
              id: { type: "string" },
              type: {
                type: "string",
                example: "STEP_COMPLETED",
                description:
                  "EXECUTION_CREATED, EXECUTION_COMPLETED, EXECUTION_CANCELLED, EXECUTION_JUMPED, ASSIGNMENT_RESOLVED, ASSIGNMENT_CHANGED, " +
                  "STEP_STARTED, STEP_COMPLETED, STEP_FAILED, STEP_BLOCKED, STEP_SKIPPED, STEP_RETRIED, APPROVAL_RECEIVED, " +
                  "RULE_EXECUTED, ACTION_FAILED, EXTERNAL_EVENT, LOOP_LIMIT",
              },
              actorId: { type: "string", nullable: true, description: "null = the engine." },
              actor: { allOf: [{ $ref: "#/components/schemas/User" }], nullable: true },
              data: { type: "object" },
              createdAt: { type: "string", format: "date-time" },
            },
          },
          Runbook: {
            type: "object",
            description: "An SOP execution: one run of an SOP definition against an issue or a task.",
            properties: {
              id: { type: "string" },
              issueId: { type: "string", nullable: true },
              taskId: { type: "string", nullable: true },
              noteId: { type: "string", nullable: true },
              sopId: { type: "string", nullable: true },
              sopVersion: { type: "integer", description: "SOP version the steps were copied from." },
              title: { type: "string" },
              mode: { type: "string", enum: ["MANUAL", "AUTOMATED"] },
              status: { type: "string", enum: ["PENDING", "IN_PROGRESS", "COMPLETED", "FAILED", "SKIPPED", "BLOCKED"] },
              assignmentType: { type: "string", enum: ["ENTITY_INHERITED", "TASK_OVERRIDE", "MANUAL"], nullable: true },
              currentStepId: { type: "string", nullable: true },
              startedAt: { type: "string", format: "date-time", nullable: true },
              completedAt: { type: "string", format: "date-time", nullable: true },
              createdAt: { type: "string", format: "date-time" },
              updatedAt: { type: "string", format: "date-time" },
              steps: { type: "array", items: { $ref: "#/components/schemas/RunbookStep" } },
              events: { type: "array", items: { $ref: "#/components/schemas/RunbookEvent" } },
              progress: {
                type: "object",
                properties: {
                  completed: { type: "integer", description: "VERIFIED + SKIPPED." },
                  total: { type: "integer" },
                  percent: { type: "integer" },
                  currentStepId: { type: "string", nullable: true },
                  completedStepIds: { type: "array", items: { type: "string" } },
                  skippedStepIds: { type: "array", items: { type: "string" } },
                  pendingStepIds: { type: "array", items: { type: "string" } },
                  inProgressStepIds: { type: "array", items: { type: "string" } },
                  failedStepIds: { type: "array", items: { type: "string" } },
                  blockedStepIds: { type: "array", items: { type: "string" } },
                },
              },
            },
          },
          ExecutionSummary: {
            type: "object",
            properties: {
              id: { type: "string" },
              status: { type: "string" },
              assignmentType: { type: "string", nullable: true },
              sopVersion: { type: "integer" },
              issue: { type: "object", nullable: true },
              task: { type: "object", nullable: true },
              currentStep: { type: "object", nullable: true },
              progress: { type: "object", properties: { completed: { type: "integer" }, total: { type: "integer" } } },
            },
          },
          IssueDetail: {
            type: "object",
            properties: {
              id: { type: "string" },
              workspaceId: { type: "string" },
              projectId: { type: "string" },
              number: { type: "integer" },
              key: { type: "string", example: "AUTH-104" },
              type: { type: "string", enum: ["STORY", "TASK", "BUG", "SECURITY", "SPIKE"] },
              title: { type: "string" },
              description: { type: "string", description: "Markdown." },
              status: { type: "string", enum: ["BACKLOG", "TODO", "IN_PROGRESS", "IN_REVIEW", "DONE", "CANCELLED"] },
              priority: { type: "string", enum: ["URGENT", "HIGH", "MEDIUM", "LOW", "NONE"] },
              storyPoints: { type: "integer", nullable: true },
              labels: { type: "array", items: { type: "string" } },
              position: { type: "number", description: "Sort order within a board column." },
              estimateMinutes: { type: "integer", nullable: true },
              dueDate: { type: "string", format: "date-time", nullable: true },
              slaDueAt: { type: "string", format: "date-time", nullable: true },
              resolvedAt: { type: "string", format: "date-time", nullable: true, description: "Set when status becomes DONE." },
              assigneeId: { type: "string", nullable: true },
              reporterId: { type: "string" },
              parentId: { type: "string", nullable: true },
              componentId: { type: "string", nullable: true },
              epicId: { type: "string", nullable: true },
              sprintId: { type: "string", nullable: true },
              releaseId: { type: "string", nullable: true },
              createdAt: { type: "string", format: "date-time" },
              updatedAt: { type: "string", format: "date-time" },
              project: { type: "object", properties: { id: { type: "string" }, key: { type: "string" }, name: { type: "string" } } },
              assignee: { allOf: [{ $ref: "#/components/schemas/User" }], nullable: true },
              reporter: { $ref: "#/components/schemas/User" },
              component: { type: "object", nullable: true },
              epic: { type: "object", nullable: true },
              sprint: { type: "object", nullable: true },
              release: { type: "object", nullable: true },
              parent: { allOf: [{ $ref: "#/components/schemas/IssueRef" }], nullable: true },
              subtasks: { type: "array", items: { allOf: [{ $ref: "#/components/schemas/IssueRef" }, { type: "object", properties: { assignee: { allOf: [{ $ref: "#/components/schemas/User" }], nullable: true } } }] } },
              subtaskProgress: { type: "object", properties: { done: { type: "integer" }, total: { type: "integer" } } },
              acceptanceCriteria: { type: "array", items: { $ref: "#/components/schemas/AcceptanceCriterion" } },
              acceptanceProgress: { type: "object", properties: { done: { type: "integer" }, total: { type: "integer" } } },
              relations: { type: "array", items: { $ref: "#/components/schemas/IssueRelation" } },
              watchers: { type: "array", items: { $ref: "#/components/schemas/User" } },
              isWatching: { type: "boolean" },
              runbooks: { type: "array", items: { $ref: "#/components/schemas/Runbook" } },
              devLinks: { type: "array", items: { $ref: "#/components/schemas/DevLink" } },
              timeTracking: { type: "object", properties: { estimateMinutes: { type: "integer", nullable: true }, loggedMinutes: { type: "integer" }, remainingMinutes: { type: "integer", nullable: true } } },
              _count: { type: "object", properties: { comments: { type: "integer" }, attachments: { type: "integer" }, workLogs: { type: "integer" } } },
            },
          },
          IssueComment: {
            type: "object",
            properties: {
              id: { type: "string" },
              issueId: { type: "string" },
              authorId: { type: "string" },
              parentId: { type: "string", nullable: true, description: "Set for replies." },
              body: { type: "string", description: "Markdown." },
              editedAt: { type: "string", format: "date-time", nullable: true },
              createdAt: { type: "string", format: "date-time" },
              author: { $ref: "#/components/schemas/User" },
            },
          },
          WorkLog: {
            type: "object",
            properties: {
              id: { type: "string" },
              issueId: { type: "string" },
              userId: { type: "string" },
              minutes: { type: "integer" },
              note: { type: "string" },
              startedAt: { type: "string", format: "date-time" },
              createdAt: { type: "string", format: "date-time" },
              updatedAt: { type: "string", format: "date-time" },
              user: { $ref: "#/components/schemas/User" },
            },
          },
          IssueAttachment: {
            type: "object",
            properties: {
              id: { type: "string" },
              issueId: { type: "string" },
              uploaderId: { type: "string" },
              storage: {
                type: "string",
                enum: ["UPLOAD", "LINK"],
                description: "UPLOAD: stored by this API, url is its download endpoint. LINK: external URL.",
              },
              fileName: { type: "string" },
              mimeType: { type: "string" },
              sizeBytes: { type: "integer" },
              url: { type: "string" },
              createdAt: { type: "string", format: "date-time" },
              uploader: { $ref: "#/components/schemas/User" },
            },
          },
          IssueActivity: {
            type: "object",
            properties: {
              id: { type: "string" },
              issueId: { type: "string" },
              actorId: { type: "string", nullable: true },
              type: { type: "string", enum: ["CREATED", "FIELD_CHANGED", "COMMENT_ADDED", "WORK_LOGGED", "ATTACHMENT_ADDED", "RELATION_ADDED", "RELATION_REMOVED", "RUNBOOK_ATTACHED", "RUNBOOK_STEP_UPDATED", "DEV_LINK_ADDED"] },
              data: { type: "object", description: "Depends on type, e.g. FIELD_CHANGED → { field, from, to }." },
              createdAt: { type: "string", format: "date-time" },
              actor: { allOf: [{ $ref: "#/components/schemas/User" }], nullable: true },
            },
          },
          Notification: {
            type: "object",
            properties: {
              id: { type: "string" },
              userId: { type: "string" },
              actorId: { type: "string", nullable: true },
              type: { type: "string", enum: ["MENTION", "ASSIGNED"] },
              workspaceId: { type: "string", nullable: true },
              issueId: { type: "string", nullable: true },
              commentId: { type: "string", nullable: true },
              data: {
                type: "object",
                description: "Snapshot for display: { issueKey, issueTitle, excerpt? }.",
              },
              readAt: { type: "string", format: "date-time", nullable: true },
              createdAt: { type: "string", format: "date-time" },
              actor: { allOf: [{ $ref: "#/components/schemas/User" }], nullable: true },
              issue: { allOf: [{ $ref: "#/components/schemas/IssueRef" }], nullable: true },
            },
          },
          NoteSearchHit: {
            type: "object",
            properties: {
              id: { type: "string" },
              title: { type: "string" },
              parentId: { type: "string", nullable: true },
              updatedAt: { type: "string", format: "date-time" },
              rank: { type: "number", description: "Postgres ts_rank_cd relevance score." },
              snippet: { type: "string", description: "HTML-highlighted content excerpt." },
              breadcrumb: {
                type: "array",
                description: "Ancestor chain, root-first, excluding the note itself.",
                items: {
                  type: "object",
                  properties: {
                    id: { type: "string" },
                    title: { type: "string" },
                  },
                },
              },
            },
          },
        },
      },
      security: [],
    },
  });
};
